//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleCountSystem__CSS_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CyclecountsystemEntities : DbContext
    {
        public CyclecountsystemEntities()
            : base("name=CyclecountsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_Akun> TB_Akun { get; set; }
        public virtual DbSet<TB_Cyclecount> TB_Cyclecount { get; set; }
        public virtual DbSet<TB_Email> TB_Email { get; set; }
        public virtual DbSet<TB_Inventory> TB_Inventory { get; set; }
        public virtual DbSet<TB_Role> TB_Role { get; set; }
    }
}
