//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleCountSystem__CSS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cyclecount
    {
        public int Id_Cyclecount { get; set; }
        public string Id_Material { get; set; }
        public string Batch_no { get; set; }
        public string bin { get; set; }
        public string Data_aktual { get; set; }
        public string SelisihQty { get; set; }
        public string Persentase { get; set; }
        public Nullable<System.DateTime> Date_count { get; set; }
        public Nullable<int> Id_akun { get; set; }
    
        public virtual TB_Akun TB_Akun { get; set; }
    }
}
