//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleCountSystem__CSS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Akun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Akun()
        {
            this.TB_Cyclecount = new HashSet<TB_Cyclecount>();
            this.TB_Inventory = new HashSet<TB_Inventory>();
        }
    
        public int Id_akun { get; set; }
        public string windows_account { get; set; }
        public Nullable<int> Id_role { get; set; }
    
        public virtual TB_Role TB_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Cyclecount> TB_Cyclecount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Inventory> TB_Inventory { get; set; }
    }
}
